title: <p align="center"> Uday Kiran Kavaturu </p>
logo: /assets/img/uday.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/udaykiran19491//">LinkedIn</a> |
  <a href="https://github.com/udaykirankavaturu">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
Also actively developing web apps at [x]cube LABS.
  <br>
  </p>



theme: jekyll-theme-minimal
